server:
  port: 8090
### Spring ###
spring:
  security:
    user:
      name: "user"
      password: "password"
  application:
    name: "authorization-service"
  cloud:
    vault:
      enabled: on
      token: "demo-token"
      uri: "http://127.0.0.1:8200"
  docker:
    compose:
      enabled: on
      stop:
        command: down
      readiness:
        tcp:
          read-timeout: "2s"
          connect-timeout: "2s"
      file: "samples/dynamic-vault-jwks-authorization-server/compose.yaml"
### Logging ###
logging:
  level:
    root: info
### Dynamic JWKS ###
dynamic-jwks:
  key-store:
    alias: "${random.uuid}"
    password: "${random.uuid}-${random.long}"
  vault:
    enabled: on
    versioned-kv:
      certificate-path: "${random.uuid}"
    pki:
      certificate-common-name: "${random.uuid}"
