services:

  redis:
    expose:
      - "6379:6379"
    ports:
      - "6379:6379"
    image: "redis:7-alpine"
    container_name: "redis-container"
    networks:
      - "dynamic-redis-jwks-authorization-server-network"

networks:
  dynamic-redis-jwks-authorization-server-network:
    name: "dynamic-redis-jwks-authorization-server-network"
