services:

  redis:
    image: "redis:7-alpine"
    ports:
      - "127.0.0.1:6379:6379"
    container_name: "redis-container"
    networks:
      - "dynamic-redis-jwks-authorization-server-network"

networks:
  dynamic-redis-jwks-authorization-server-network:
    name: "dynamic-redis-jwks-authorization-server-network"
