name: ci
on: [ push ]
jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v1
  unit-test:
    needs: validation
    runs-on: ubuntu-latest
    name: "Run Unit Tests"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: corretto
      - uses: docker/setup-buildx-action@v3
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: clean test
      - name: "Directories list"
        run: ls
      - uses: codecov/codecov-action@v3
        with:
          verbose: true
          directory: "./"
          token: ${{ secrets.CODECOV_TOKEN }}
          files: "./dynamic-redis-jwks-spring-boot-starter/build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.xml,
                  ./dynamic-vault-jwks-spring-boot-starter/build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.xml"
  integration-test:
    needs: unit-test
    runs-on: ubuntu-latest
    name: "Run Integration Tests"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: corretto
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: clean integrationTest
      - name: "Directories list"
        run: ls
      - uses: codecov/codecov-action@v3
        with:
          verbose: true
          directory: "./"
          token: ${{ secrets.CODECOV_TOKEN }}
          files: "./dynamic-redis-jwks-spring-boot-starter/build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.xml,
                  ./dynamic-vault-jwks-spring-boot-starter/build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.xml"
