name: Dynamic JWKS Release CI/CD
on: [ release ]
jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
  unit-test:
    needs: validation
    runs-on: ubuntu-latest
    name: "Run Unit Tests"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto
      - uses: docker/setup-buildx-action@v3
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: clean test
  integration-test:
    needs: unit-test
    runs-on: ubuntu-latest
    name: "Run Integration Tests"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: clean integrationTest
  release:
    runs-on: ubuntu-latest
    needs: integration-test
    if: contains(github.ref, '/release/')
    name: "Publish To Maven Central"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: clean build publish -x test -x integrationTest
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          MAVEN_GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
