name: ci
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
permissions:
  contents: read
jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: gradle/actions/wrapper-validation@v5
  verification:
    needs: validation
    runs-on: ubuntu-latest
    name: "Verify JReleaser Config"
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: liberica
      - uses: gradle/actions/setup-gradle@v5
      - run: ./gradlew clean jreleaserConfig --build-cache
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          MAVEN_GPG_PUBLIC_KEY: ${{ secrets.MAVEN_GPG_PUBLIC_KEY }}
          MAVEN_GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
  unit-test:
    needs: verification
    runs-on: ubuntu-latest
    name: "Run Unit Tests"
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: liberica
      - uses: docker/setup-buildx-action@v3
      - uses: gradle/actions/setup-gradle@v5
      - run: ./gradlew clean test testCodeCoverageReport --build-cache
      - uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          files: "testCodeCoverageReport.xml"
          directory: "./build/reports/jacoco/testCodeCoverageReport"
  integration-test:
    needs: unit-test
    runs-on: ubuntu-latest
    name: "Run Integration Tests"
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: liberica
      - uses: gradle/actions/setup-gradle@v5
      - run: ./gradlew clean integrationTest integrationTestCodeCoverageReport --build-cache
      - uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          files: "integrationTestCodeCoverageReport.xml"
          directory: "./build/reports/jacoco/integrationTestCodeCoverageReport"
