name: Vault based dynamic JWKS CI

on:
  - push

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Make gradlew executable
        run: chmod +x gradlew
      - name: Execute Gradle test
        run: gradlew clean test
